"use client";

import { ChakraProvider } from "@chakra-ui/react";
import "./globals.css";
import { ComponentsProvider } from "./context/ComponentsContext";
import { EditorProvider } from "./context/EditorContext";

// export const metadata = {
//   title: "Page builder demo",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <ChakraProvider>
          <ComponentsProvider>
            <EditorProvider>{children}</EditorProvider>
          </ComponentsProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
